/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/dOYBQ43D0Ot
 */
import {
  CardTitle,
  CardHeader,
  CardContent,
  CardFooter,
  Card,
} from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";

export function challengeCard() {
  return (
    <Card key="1">
      <CardHeader>
        <CardTitle className="text-lg font-bold">Web/Problem Name</CardTitle>
        <div className="flex space-x-2">
          <div className="inline-flex items-center bg-blue-600 text-white text-xs px-2 py-1 rounded">
            Dynamic
          </div>
          <div className="inline-flex items-center bg-green-500 text-white text-xs px-2 py-1 rounded">
            Running
          </div>
        </div>
      </CardHeader>
      <CardContent className="space-y-2 py-4">
        <p className="text-sm text-gray-600">
          Description of the problem. This should give the users an idea of what
          the challenge entails.
        </p>
        <div className="space-y-2 flex items-center justify-between h-[100px]">
          <Input
            className="flex-grow mr-2"
            id="flag"
            placeholder="Enter your flag here..."
          />
          <Button className="bg-blue-600 text-white">Submit</Button>
        </div>
      </CardContent>
      <CardFooter className="flex justify-between items-center bg-gray-100 py-4 dark:bg-gray-800">
        <Button className="bg-transparent  text-gray-600 hover:bg-gray-100 dark:hover:bg-gray-700">
          Download
          <div className="inline-flex items-center bg-green-500 text-white text-xs px-2 py-1 rounded ml-2">
            a.out
          </div>
          <div className="inline-flex items-center bg-yellow-500 text-white text-xs px-2 py-1 rounded ml-2">
            output.txt
          </div>
        </Button>
        <Button className="bg-blue-500 text-white">Instance Start</Button>
      </CardFooter>
    </Card>
  );
}
